spring:
  application:
    name: ai-code-generate
  profiles:
    active: local # 引入local文件配置
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/code_genertate
    username: root
    password: 123456
server:
  servlet:
    context-path: /api
  port: 8095

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.codegenerate.aicodegenerate.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn






