spring:
  application:
    name: ai-code-generate
server:
  servlet:
    context-path: /api
  port: 8095

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.codegenerate.aicodegenerate.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

