# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-9b5884fc1d8646e7b22aaced300eeb66
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true
      max-tokens: 8192  # 每个汉字约等于0.6token
      response-format: json_object # 强制json格式输出
      max-retries: 0 # langchain会自动重试
    streaming-chat-model:  # 切换为流式输出
      base-url: https://api.deepseek.com
      api-key: sk-9b5884fc1d8646e7b22aaced300eeb66
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true
      max-tokens: 8192  # 每个汉字约等于0.6token
      # response-format: json_object # 强制json格式输出
      max-retries: 0 # langchain会自动重试

